<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Supercluster.Lib.Domain/Supercluster.Lib.Domain.csproj" />
    <ProjectReference Include="../Supercluster.Lib.Primitives/Supercluster.Lib.Primitives.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Passport.Core.Application" />
    <InternalsVisibleTo Include="Passport.Core.Domain.Tests" />
    <InternalsVisibleTo Include="Passport.Core.Application.Tests" />
  </ItemGroup>

</Project>
