<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Gestalt.Lib.Domain/Gestalt.Lib.Domain.csproj" />
    <ProjectReference Include="../Gestalt.Lib.Primitives/Gestalt.Lib.Primitives.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Passport.Core.Application" />
    <InternalsVisibleTo Include="Passport.Core.Domain.Tests" />
    <InternalsVisibleTo Include="Passport.Core.Application.Tests" />
    <InternalsVisibleTo Include="Passport.IntegrationTests" />
  </ItemGroup>

</Project>
