import { readFileSync, readdirSync, writeFileSync, mkdirSync, statSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = resolve(__dirname, "icon-pack-src");
const outDir = resolve(__dirname, "..", "src", "components", "Icon");

interface PathShape {
  type: "path";
  d: string;
}

interface RectShape {
  type: "rect";
  x: number;
  y: number;
  width: number;
  height: number;
  rx?: number;
}

interface EllipseShape {
  type: "ellipse";
  cx: number;
  cy: number;
  rx: number;
  ry: number;
}

type IconShape = PathShape | RectShape | EllipseShape;

function attr(tag: string, name: string): string | undefined {
  const m = tag.match(new RegExp(`${name}="([^"]*)"`));
  return m ? m[1] : undefined;
}

function parseShape(svg: string): IconShape {
  const inner = svg.replace(/<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();

  if (inner.startsWith("<path")) {
    const d = attr(inner, "d");
    if (d === undefined) throw new Error("path element missing 'd' attribute");
    return { type: "path", d };
  }

  if (inner.startsWith("<rect")) {
    const x = Number(attr(inner, "x"));
    const y = Number(attr(inner, "y"));
    const width = Number(attr(inner, "width"));
    const height = Number(attr(inner, "height"));
    const rxRaw = attr(inner, "rx");
    const rx = rxRaw !== undefined ? Number(rxRaw) : undefined;
    return rx !== undefined
      ? { type: "rect", x, y, width, height, rx }
      : { type: "rect", x, y, width, height };
  }

  if (inner.startsWith("<ellipse")) {
    const cx = Number(attr(inner, "cx"));
    const cy = Number(attr(inner, "cy"));
    const rx = Number(attr(inner, "rx"));
    const ry = Number(attr(inner, "ry"));
    return { type: "ellipse", cx, cy, rx, ry };
  }

  throw new Error(`Unsupported shape element: ${inner.slice(0, 60)}`);
}

function shapeToTs(shape: IconShape): string {
  switch (shape.type) {
    case "path":
      return `{ type: "path", d: ${JSON.stringify(shape.d)} }`;
    case "rect":
      return `{ type: "rect", x: ${shape.x}, y: ${shape.y}, width: ${shape.width}, height: ${shape.height}${shape.rx !== undefined ? `, rx: ${shape.rx}` : ""} }`;
    case "ellipse":
      return `{ type: "ellipse", cx: ${shape.cx}, cy: ${shape.cy}, rx: ${shape.rx}, ry: ${shape.ry} }`;
  }
}

const header = [
  "// This file is generated by scripts/generate-icons.ts. Do not edit manually.",
  "// Regenerate with `pnpm generate-icons`.",
  "// Source: Game Icon Pack by Nieobie (https://nieobie.itch.io/free-icons) — CC0 1.0 Universal.",
  "",
].join("\n");

const shapeTypeBlock = [
  "export type IconShape =",
  "  | { type: \"path\"; d: string }",
  "  | { type: \"rect\"; x: number; y: number; width: number; height: number; rx?: number }",
  "  | { type: \"ellipse\"; cx: number; cy: number; rx: number; ry: number };",
].join("\n");

// --- Collect icons grouped by folder ---

const folders: Record<string, Record<string, IconShape>> = {};

for (const folder of readdirSync(srcDir)) {
  const dir = join(srcDir, folder);
  if (!statSync(dir).isDirectory()) continue;

  const icons: Record<string, IconShape> = {};
  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".svg")) continue;
    const name = file.replace(/\.svg$/, "");
    const svg = readFileSync(join(dir, file), "utf-8");
    icons[name] = parseShape(svg);
  }

  if (Object.keys(icons).length > 0) {
    folders[folder] = icons;
  }
}

const folderNames = Object.keys(folders).sort();
const allNames = folderNames
  .flatMap((folder) => Object.keys(folders[folder]))
  .sort();

mkdirSync(join(outDir, "icons"), { recursive: true });

// --- icon-data.ts: shared types + names ---

const namesBlock = `export const iconNames = [\n${allNames.map((n) => `  ${JSON.stringify(n)},`).join("\n")}\n] as const;`;

const iconDataOutput = [
  header,
  shapeTypeBlock,
  "",
  "export const ICON_VIEWBOX = \"0 0 10 10\";",
  "",
  namesBlock,
  "",
  "export type IconName = (typeof iconNames)[number];",
  "",
  "export const Icons = iconNames as readonly IconName[];",
  "",
].join("\n");

writeFileSync(join(outDir, "icon-data.ts"), iconDataOutput, "utf-8");

// --- icons/<folder>.ts: per-folder shape data ---

for (const folder of folderNames) {
  const icons = folders[folder];
  const names = Object.keys(icons).sort();
  const body = names
    .map((name) => `  ${JSON.stringify(name)}: [${shapeToTs(icons[name])}],`)
    .join("\n");

  const fileOutput = [
    header,
    'import type { IconShape } from "../icon-data";',
    "",
    `export const icons: Record<string, IconShape[]> = {\n${body}\n};`,
    "",
  ].join("\n");

  writeFileSync(join(outDir, "icons", `${folder}.ts`), fileOutput, "utf-8");
}

// --- registry.ts: name -> folder loader ---

const folderLoaderLines = folderNames
  .map((f) => `  ${JSON.stringify(f)}: () => import("./icons/${f}"),`)
  .join("\n");

const nameToFolderLines = folderNames
  .flatMap((folder) =>
    Object.keys(folders[folder])
      .sort()
      .map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(folder)},`),
  )
  .join("\n");

const registryOutput = [
  header,
  'import type { IconShape } from "./icon-data";',
  "",
  "interface FolderModule {",
  "  icons: Record<string, IconShape[]>;",
  "}",
  "",
  "const folderLoaders: Record<string, () => Promise<FolderModule>> = {",
  folderLoaderLines,
  "};",
  "",
  "const nameToFolder: Record<string, string> = {",
  nameToFolderLines,
  "};",
  "",
  "export async function loadIconShapes(name: string): Promise<IconShape[] | undefined> {",
  "  const folder = nameToFolder[name];",
  "  if (!folder) return undefined;",
  "  const loader = folderLoaders[folder];",
  "  if (!loader) return undefined;",
  "  const mod = await loader();",
  "  return mod.icons[name];",
  "}",
  "",
].join("\n");

writeFileSync(join(outDir, "registry.ts"), registryOutput, "utf-8");

console.log(
  `Wrote ${allNames.length} icons across ${folderNames.length} folder chunks`,
);
