<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Passport.Core.Application/Passport.Core.Application.csproj" />
    <ProjectReference Include="../Supercluster.Lib.Infrastructure.Email/Supercluster.Lib.Infrastructure.Email.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Passport.IntegrationTests" />
  </ItemGroup>

</Project>