// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Passport.Infrastructure.Persistence;

#nullable disable

namespace Passport.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PassportDbContext))]
    [Migration("20260709022852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Passport.Core.Domain.Entities.RecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Purpose");

                    b.ToTable("RecoveryCodes");
                });

            modelBuilder.Entity("Passport.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Passport.Core.Domain.Entities.User", b =>
                {
                    b.OwnsMany("Passport.Core.Domain.Entities.PasskeyCredential", "Passkeys", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<byte[]>("CredentialId")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<string>("DeviceName")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.Property<uint>("SignCount")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("CredentialId")
                                .IsUnique();

                            b1.HasIndex("UserId");

                            b1.ToTable("PasskeyCredential");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("Passport.Core.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientId")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("IssuedAt")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("TokenHash")
                                .IsUnique();

                            b1.HasIndex("UserId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Passkeys");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
