<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Builder" />
    <Using Include="Microsoft.AspNetCore.Http" />
    <Using Include="Microsoft.AspNetCore.Routing" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Gestalt.Lib.Presentation.Http/Gestalt.Lib.Presentation.Http.csproj" />
    <ProjectReference Include="../Passport.Core.Application/Passport.Core.Application.csproj" />
  </ItemGroup>

</Project>