<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Supercluster.Lib.Application/Supercluster.Lib.Application.csproj" />
    <ProjectReference Include="../Passport.Core.Domain/Passport.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Passport.Core.Application.Tests" />
  </ItemGroup>

</Project>