using System.Net.Http.Json;
using Xunit;
using System.Text.Json;

namespace Passport.IntegrationTests.Flows;

public class AuthenticationFlowTests : IAsyncLifetime
{
    private readonly TestHost _host;
    private HttpClient _client = null!;

    public AuthenticationFlowTests()
    {
        _host = TestHostFactory.Create();
    }

    public async Task InitializeAsync()
    {
        _client = _host.CreateDefaultClient();
        await _host.EnsureDatabaseAsync();
    }

    public async Task DisposeAsync()
    {
        _client.Dispose();
        _host.Dispose();
    }

    private async Task RegisterUserAsync(string email)
    {
        await _client.PostAsJsonAsync("/api/v1/auth/register/begin", new { Email = email });
        await _client.PostAsJsonAsync("/api/v1/auth/register/complete", new { Email = email, AttestationJson = "{}" });
    }

    [Fact]
    public async Task LoginFlow_ValidCredentials_ReturnsTokens()
    {
        await RegisterUserAsync("test@example.com");
        // Verify email — the code is generated by the handler
        var code = _host.GetLastCode();
        Assert.NotNull(code);
        var verifyResponse = await _client.PostAsJsonAsync("/api/v1/auth/register/verify-email", new { Email = "test@example.com", Code = code });
        Assert.True(verifyResponse.IsSuccessStatusCode);

        var beginResponse = await _client.PostAsJsonAsync("/api/v1/auth/login/begin", new { Email = "test@example.com" });
        Assert.True(beginResponse.IsSuccessStatusCode);

        var completeResponse = await _client.PostAsJsonAsync("/api/v1/auth/login/complete", new { Email = "test@example.com", AssertionJson = "{}" });
        var body = await completeResponse.Content.ReadAsStringAsync();
        Assert.True(completeResponse.IsSuccessStatusCode, $"Login complete returned {completeResponse.StatusCode}: {body}");

        var result = JsonSerializer.Deserialize<JsonElement>(body);
        Assert.True(result.TryGetProperty("accessToken", out _));
        Assert.True(result.TryGetProperty("refreshToken", out _));
    }

    [Fact]
    public async Task LoginFlow_UserNotFound_ReturnsNotFound()
    {
        var response = await _client.PostAsJsonAsync("/api/v1/auth/login/begin", new { Email = "unknown@example.com" });

        Assert.Equal(System.Net.HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task LoginFlow_UnverifiedEmail_ReturnsUnauthorized()
    {
        await RegisterUserAsync("unverified@example.com");

        var response = await _client.PostAsJsonAsync("/api/v1/auth/login/begin", new { Email = "unverified@example.com" });

        Assert.Equal(System.Net.HttpStatusCode.Unauthorized, response.StatusCode);
    }
}